dist: trusty
sudo: false
language: ruby
cache: bundler

rvm:
  - 2.3
  - 2.4
  - 2.5

matrix:
  fast_finish: true

before_install: gem update bundler
bundler_args: --jobs 3
install: bundle install --jobs 3

script:
  - bundle exec rubocop --fail-level autocorrect
  - bundle exec rspec
