language: ruby
sudo: false
cache: bundler
rvm:
  # - ruby-head
  - 2.1
  - 2.2
  - 2.3
matrix:
  fast_finish: true
  # WWTD doesn't support allow_failures... yet
  # allow_failures:
  #   - rvm: ruby-head
script: bundle exec rspec
notifications:
  email:
    on_success: never
    on_failure: never
